import type { ModelSignal, RankingMove, TimelineStep, WatchCompany } from './types'

export const companies: WatchCompany[] = [
  {
    name: 'OpenAI',
    family: 'GPT',
    focus: '通用、多模态、推理、工具调用',
    status: '高优先级',
    score: 98,
    activeSignals: 8,
    accent: '#61f4d7',
  },
  {
    name: 'Anthropic',
    family: 'Claude Sonnet / Opus',
    focus: '长文本、代码、深度推理',
    status: '高优先级',
    score: 96,
    activeSignals: 6,
    accent: '#ffb86b',
  },
  {
    name: 'Google',
    family: 'Gemini Pro',
    focus: '多模态、搜索生态、上下文窗口',
    status: '高优先级',
    score: 94,
    activeSignals: 5,
    accent: '#75a7ff',
  },
  {
    name: 'xAI',
    family: 'Grok',
    focus: '实时信息、产品化、工具型模型',
    status: '观察加速',
    score: 88,
    activeSignals: 4,
    accent: '#e7ecff',
  },
  {
    name: 'DeepSeek',
    family: 'DeepSeek',
    focus: '开源、推理、性价比',
    status: '国产核心',
    score: 91,
    activeSignals: 5,
    accent: '#45d18a',
  },
  {
    name: 'Kimi',
    family: 'Kimi K',
    focus: '中文、长上下文、Agent',
    status: '国产核心',
    score: 86,
    activeSignals: 3,
    accent: '#8bd4ff',
  },
  {
    name: 'GLM',
    family: 'GLM',
    focus: '中文通用、多模态、企业生态',
    status: '国产核心',
    score: 84,
    activeSignals: 3,
    accent: '#c7a6ff',
  },
  {
    name: 'Qwen',
    family: 'Qwen',
    focus: '开源生态、中文、代码',
    status: '重要补充',
    score: 89,
    activeSignals: 4,
    accent: '#3ee0ff',
  },
]

export const signals: ModelSignal[] = [
  {
    id: 1,
    company: 'OpenAI',
    model: 'GPT-5.5',
    title: '第三方产品侧出现 GPT-5.5 选项',
    level: 'platform',
    confidence: 78,
    source: '第三方产品接入',
    stage: '接入信号',
    time: '12 分钟前',
    impact: '需要等待官方模型文档确认命名和 API 可用性。',
  },
  {
    id: 2,
    company: 'Anthropic',
    model: 'Claude Opus 4.8',
    title: 'Opus 系列出现新版本信号',
    level: 'document',
    confidence: 72,
    source: '文档/产品列表变化',
    stage: '文档信号',
    time: '36 分钟前',
    impact: '重点关注上下文、代码能力和价格变化。',
  },
  {
    id: 3,
    company: 'Google',
    model: 'Gemini 3.1 Pro',
    title: 'Gemini Pro 系列进入重点观察窗口',
    level: 'official',
    confidence: 91,
    source: '官方发布节奏 + 榜单变化',
    stage: '官方确认',
    time: '1 小时前',
    impact: '多模态和长上下文能力可能继续影响榜单。',
  },
  {
    id: 4,
    company: 'xAI',
    model: 'Grok 4.3',
    title: 'Grok 版本线在第三方入口持续更新',
    level: 'platform',
    confidence: 74,
    source: '产品侧接入',
    stage: '第三方接入',
    time: '2 小时前',
    impact: '关注实时信息能力和 API 开放节奏。',
  },
  {
    id: 5,
    company: 'DeepSeek',
    model: 'DeepSeek V4 Pro',
    title: 'DeepSeek 新版本进入中文社区讨论',
    level: 'community',
    confidence: 61,
    source: '社区传闻',
    stage: '低可信传闻',
    time: '3 小时前',
    impact: '仅作为观察，不应直接写入已发布模型库。',
  },
  {
    id: 6,
    company: 'Kimi',
    model: 'Kimi K2.6',
    title: 'Kimi K 系列在开源模型池被标记为重点',
    level: 'platform',
    confidence: 76,
    source: '模型平台索引',
    stage: '第三方接入',
    time: '4 小时前',
    impact: '中文长上下文与 Agent 能力值得单独追踪。',
  },
  {
    id: 7,
    company: 'GLM',
    model: 'GLM 5.2',
    title: 'GLM 5.2 在产品模型列表中出现',
    level: 'platform',
    confidence: 79,
    source: '第三方产品接入',
    stage: '接入信号',
    time: '5 小时前',
    impact: '需要核对官方 API 文档与价格表。',
  },
]

export const rankingMoves: RankingMove[] = [
  { model: 'GPT-5.5', company: 'OpenAI', board: '综合能力', change: 3, score: '98.4' },
  { model: 'Claude Opus 4.8', company: 'Anthropic', board: '代码推理', change: 2, score: '97.1' },
  { model: 'Gemini 3.1 Pro', company: 'Google', board: '多模态', change: 1, score: '96.6' },
  { model: 'DeepSeek V4 Pro', company: 'DeepSeek', board: '性价比', change: 5, score: '95.8' },
  { model: 'Kimi K2.6', company: 'Kimi', board: '中文长文', change: -1, score: '92.7' },
]

export const timeline: TimelineStep[] = [
  { label: '首次信号', status: 'done', detail: '产品列表、模型 ID 或仓库出现' },
  { label: '证据聚合', status: 'done', detail: '官方、平台、榜单、社区交叉验证' },
  { label: '可信度评级', status: 'active', detail: '按来源权重计算可信等级' },
  { label: '正式发布', status: 'pending', detail: '等待官方博客/API 文档确认' },
  { label: '榜单追踪', status: 'pending', detail: '进入 Arena、OpenCompass 等榜单' },
]

export const sourceTypes = [
  { label: '官方确认', level: 'official', value: 94 },
  { label: 'API 可用', level: 'platform', value: 88 },
  { label: '文档信号', level: 'document', value: 72 },
  { label: '社区传闻', level: 'community', value: 48 },
] as const
