import type { FrontierSignal, ReleaseFrame } from './types'

export const categories = [
  '全部',
  '模型',
  'AI 编程',
  'Agent',
  'Skill / 插件',
  '平台',
]

export const signals: FrontierSignal[] = [
  {
    id: 'gpt-55',
    provider: 'OpenAI',
    name: 'GPT-5.5',
    category: '模型',
    level: 'official',
    confidence: 98,
    firstSeen: '18 分钟前',
    lastUpdate: '28 秒前',
    releaseWindow: '约 2-4 周',
    title: 'OpenAI 下一代前沿模型信号',
    summary: '第三方产品侧已出现 GPT-5.5，可作为强产品接入信号，但仍需官方模型文档确认最终命名。',
    lane: 0,
    offset: 6,
    accent: '#63f7d4',
    sources: [
      { name: 'OpenAI 官方', type: 'official', detail: '官方渠道释放夏季发布信号', strength: 93 },
      { name: 'OpenAI 文档', type: 'docs', detail: '文档和 SDK 需要继续监控', strength: 82 },
      { name: '第三方产品', type: 'platform', detail: '产品侧模型选择器出现该版本', strength: 88 },
      { name: '社区观察', type: 'rumor', detail: '社区讨论热度上升', strength: 54 },
    ],
  },
  {
    id: 'codex',
    provider: 'OpenAI',
    name: 'Codex',
    category: 'AI 编程',
    level: 'platform',
    confidence: 94,
    firstSeen: '32 分钟前',
    lastUpdate: '2 分钟前',
    releaseWindow: '持续更新',
    title: 'Codex 编程代理生态需要独立追踪',
    summary: 'Codex 不只是模型入口，而是 AI 编程工作流本身；需要追踪 CLI、IDE、任务线程、工具调用和 Skill 能力变化。',
    lane: 1,
    offset: 20,
    accent: '#8eb9ff',
    sources: [
      { name: 'OpenAI 开发者文档', type: 'docs', detail: '追踪 Codex、工具调用和开发者工作流变化', strength: 86 },
      { name: '产品侧更新', type: 'platform', detail: '桌面端、CLI 和任务线程能力需要持续观察', strength: 88 },
      { name: '社区反馈', type: 'rumor', detail: '开发者使用体验变化可作为低权重信号', strength: 48 },
    ],
  },
  {
    id: 'claude-code',
    provider: 'Anthropic',
    name: 'Claude Code',
    category: 'AI 编程',
    level: 'docs',
    confidence: 92,
    firstSeen: '1 小时前',
    lastUpdate: '4 分钟前',
    releaseWindow: '持续更新',
    title: 'Claude Code 成为 Anthropic 工具线重点',
    summary: 'Claude Code 代表模型能力向真实开发环境迁移，版本、权限、上下文和终端集成都值得长期追踪。',
    lane: 2,
    offset: 34,
    accent: '#ffb86b',
    sources: [
      { name: 'Claude 文档', type: 'docs', detail: '命令行、权限和项目上下文说明持续变化', strength: 84 },
      { name: '官方发布', type: 'official', detail: 'Anthropic 工具产品线的正式更新', strength: 80 },
      { name: '开发者社区', type: 'rumor', detail: '插件与工作流实践更新较快，需要降权处理', strength: 45 },
    ],
  },
  {
    id: 'zed-code',
    provider: 'Zed',
    name: 'Zed Code / Zcode',
    category: 'AI 编程',
    level: 'platform',
    confidence: 78,
    firstSeen: '2 小时前',
    lastUpdate: '9 分钟前',
    releaseWindow: '约 1-3 周',
    title: 'Zed 系 AI 编程体验进入观察池',
    summary: 'Zed/Zcode 这类编辑器原生 AI 能力会影响开发者选择，重点观察本地编辑体验、协作和模型接入。',
    lane: 3,
    offset: 48,
    accent: '#3ee0ff',
    sources: [
      { name: '产品更新', type: 'platform', detail: '编辑器端 AI 能力和模型接入变化', strength: 73 },
      { name: 'GitHub / Release', type: 'docs', detail: '版本发布和扩展能力需要自动追踪', strength: 72 },
      { name: '社区讨论', type: 'rumor', detail: '名称和路线图需要等待官方确认', strength: 42 },
    ],
  },
  {
    id: 'mcp-skills',
    provider: 'MCP Ecosystem',
    name: 'MCP / Skills',
    category: 'Skill / 插件',
    level: 'docs',
    confidence: 88,
    firstSeen: '3 小时前',
    lastUpdate: '12 分钟前',
    releaseWindow: '持续更新',
    title: 'Skill 与 MCP 生态正在成为关键层',
    summary: '未来不只是模型强弱，工具调用、连接器、Skill、MCP Server 会决定 AI 能否真正处理复杂任务。',
    lane: 4,
    offset: 25,
    accent: '#b79cff',
    sources: [
      { name: '协议文档', type: 'docs', detail: 'MCP、工具规范和权限模型需要跟踪', strength: 83 },
      { name: '插件市场', type: 'platform', detail: '新连接器和 Skill 的上线速度很快', strength: 81 },
      { name: '开源仓库', type: 'platform', detail: '社区 MCP Server 增长可作为生态热度', strength: 74 },
    ],
  },
  {
    id: 'agent-runtime',
    provider: 'OpenAI / Anthropic / LangChain',
    name: 'Agent Runtime',
    category: 'Agent',
    level: 'docs',
    confidence: 84,
    firstSeen: '4 小时前',
    lastUpdate: '14 分钟前',
    releaseWindow: '持续更新',
    title: 'Agent 运行时与工具权限成为前沿层',
    summary: 'Agent 不只是聊天界面，需要持续追踪任务执行、浏览器/终端能力、工具权限、记忆、沙箱和可观测性。',
    lane: 4,
    offset: 62,
    accent: '#f7d774',
    sources: [
      { name: '开发者文档', type: 'docs', detail: 'Agent SDK、工具调用、沙箱和权限模型的变更', strength: 82 },
      { name: '产品侧能力', type: 'platform', detail: '能否跨应用执行任务会直接影响真实可用性', strength: 78 },
      { name: '开源框架', type: 'platform', detail: 'LangChain、AutoGen 等框架更新可作为生态热度参考', strength: 70 },
    ],
  },
  {
    id: 'openrouter-rankings',
    provider: 'OpenRouter / LMArena',
    name: 'Rankings Signal',
    category: '平台',
    level: 'platform',
    confidence: 86,
    firstSeen: '5 小时前',
    lastUpdate: '16 分钟前',
    releaseWindow: '每日更新',
    title: '榜单变化需要和发布信号分开看',
    summary: '模型排名可以接入 OpenRouter、LMArena、Hugging Face 等平台，但不能替代官方发布、文档变更和产品接入证据。',
    lane: 5,
    offset: 12,
    accent: '#ff6fd8',
    sources: [
      { name: 'OpenRouter Rankings', type: 'platform', detail: '模型调用、价格、可用性和排名变化', strength: 83 },
      { name: 'LMArena', type: 'platform', detail: '社区偏好榜单可作为能力趋势参考', strength: 76 },
      { name: 'Hugging Face', type: 'platform', detail: '模型、数据集和论文热度提供补充信号', strength: 72 },
    ],
  },
  {
    id: 'deepseek-v4-pro',
    provider: 'DeepSeek',
    name: 'DeepSeek V4 Pro',
    category: '模型',
    level: 'rumor',
    confidence: 76,
    firstSeen: '7 小时前',
    lastUpdate: '18 分钟前',
    releaseWindow: '约 4-8 周',
    title: 'DeepSeek Pro 信号进入观察模式',
    summary: '需要把社区传闻、开源仓库、API 接入和官方公告拆开处理，避免把传闻当事实。',
    lane: 5,
    offset: 58,
    accent: '#58d68d',
    sources: [
      { name: 'API 网关观察', type: 'platform', detail: '接入平台出现相关占位', strength: 73 },
      { name: '开源生态观察', type: 'platform', detail: '仓库和模型平台需要跟踪', strength: 74 },
      { name: '社区观察', type: 'rumor', detail: '讨论热度高，但证据链不足', strength: 52 },
    ],
  },
]

export const releaseFrames: ReleaseFrame[] = [
  { name: 'GPT-5.5', provider: 'OpenAI', category: '模型', confidence: 98, window: '现在', accent: '#63f7d4' },
  { name: 'Codex', provider: 'OpenAI', category: 'AI 编程', confidence: 94, window: '持续更新', accent: '#8eb9ff' },
  { name: 'Claude Code', provider: 'Anthropic', category: 'AI 编程', confidence: 92, window: '持续更新', accent: '#ffb86b' },
  { name: 'Zed Code / Zcode', provider: 'Zed', category: 'AI 编程', confidence: 78, window: '约 1-3 周', accent: '#3ee0ff' },
  { name: 'MCP / Skills', provider: 'MCP Ecosystem', category: 'Skill / 插件', confidence: 88, window: '持续更新', accent: '#b79cff' },
  { name: 'Agent Runtime', provider: 'OpenAI / Anthropic / LangChain', category: 'Agent', confidence: 84, window: '持续更新', accent: '#f7d774' },
  { name: 'Rankings Signal', provider: 'OpenRouter / LMArena', category: '平台', confidence: 86, window: '每日更新', accent: '#ff6fd8' },
  { name: 'DeepSeek V4 Pro', provider: 'DeepSeek', category: '模型', confidence: 76, window: '约 4-8 周', accent: '#58d68d' },
  { name: 'Kimi K2.6', provider: 'Kimi', category: '模型', confidence: null, window: '约 3-6 周', accent: '#ffb86b' },
  { name: 'GLM 5.2', provider: 'GLM', category: '模型', confidence: null, window: '约 5-10 周', accent: '#b79cff' },
]
