import type { FrontierIntelDataset } from './types'

export const fallbackFrontierIntelDataset: FrontierIntelDataset = {
  generatedAt: '2026-06-28T08:30:00.000Z',
  stats: {
    totalEntities: 131,
    totalSources: 40,
    verifiedSources: 12,
    updatedLabel: '静态快照',
    generatedAt: '2026-06-28T08:30:00.000Z',
    databaseStatus: '未配置',
  },
  workspaceNav: [
    { label: '情报总览', href: '#overview', legacyHref: '#radar' },
    { label: '信号矩阵', href: '#signals' },
    { label: '模型地图', href: '#model-rankings' },
    { label: 'Agent 市场', href: '#agent-rankings' },
    { label: 'Skill / 插件', href: '#tool-rankings' },
    { label: '数据洞察', href: '#source-runs' },
    { label: '榜单', href: '#rankings' },
    { label: '发布日历', href: '#calendar' },
    { label: '可信来源', href: '#sources' },
    { label: '路线图', href: '#roadmap' },
  ],
  categories: ['全部', '模型', 'AI 编程', 'Agent', 'Skill / 插件', '平台'],
  categoryMeta: {
    全部: { accent: '#10b5ab', soft: 'rgba(18, 195, 185, 0.1)', icon: 'layout-dashboard' },
    模型: { accent: '#16c8be', soft: 'rgba(22, 200, 190, 0.12)', icon: 'sparkles' },
    'AI 编程': { accent: '#4b8cff', soft: 'rgba(75, 140, 255, 0.12)', icon: 'code' },
    Agent: { accent: '#f59e0b', soft: 'rgba(245, 158, 11, 0.14)', icon: 'activity' },
    'Skill / 插件': { accent: '#b07bf7', soft: 'rgba(176, 123, 247, 0.14)', icon: 'layers' },
    平台: { accent: '#ff6fd8', soft: 'rgba(255, 111, 216, 0.12)', icon: 'chart' },
  },
  signals: [
    {
      id: 'gpt-56-sol',
      provider: 'OpenAI',
      name: 'GPT-5.6 Sol',
      category: '模型',
      level: 'official',
      confidence: 99,
      firstSeen: '2026-06-26',
      lastUpdate: '11 小时前',
      releaseWindow: '有限预览',
      title: 'GPT-5.6 Sol 进入有限预览',
      summary: 'OpenAI 官方资料确认 GPT-5.6 Sol 进入有限预览，当前应作为最高可信度发布信号追踪，并继续监控 API 命名、价格和访问范围。',
      lane: 0,
      offset: 6,
      accent: '#63f7d4',
      sources: [
        { name: 'OpenAI 公告', type: 'official', detail: '官网发布 GPT-5.6 Sol 预览说明', strength: 98, url: 'https://openai.com/news/' },
        { name: 'OpenAI Help', type: 'docs', detail: 'Help 文档说明 Sol / Terra / Luna 的有限预览', strength: 96, url: 'https://help.openai.com/' },
        { name: 'OpenAI X', type: 'social', detail: '官方社媒同步确认发布时间线', strength: 88, url: 'https://x.com/OpenAI' },
      ],
    },
    {
      id: 'gpt-56-terra',
      provider: 'OpenAI',
      name: 'GPT-5.6 Terra',
      category: '模型',
      level: 'official',
      confidence: 97,
      firstSeen: '2026-06-26',
      lastUpdate: '11 小时前',
      releaseWindow: '有限预览',
      title: 'GPT-5.6 Terra 限量开放',
      summary: 'Terra 属于 GPT-5.6 系列预览模型，需要持续追踪 ChatGPT 与 API 的账号层级、速率限制和能力边界。',
      lane: 0,
      offset: 10,
      accent: '#ff8f5f',
      sources: [
        { name: 'OpenAI Help', type: 'docs', detail: '有限预览说明中列出 Terra', strength: 96, url: 'https://help.openai.com/' },
        { name: 'OpenAI API', type: 'platform', detail: '监控模型 ID、价格和可用区域', strength: 88, url: 'https://platform.openai.com/docs/models' },
      ],
    },
    {
      id: 'gpt-56-luna',
      provider: 'OpenAI',
      name: 'GPT-5.6 Luna',
      category: '模型',
      level: 'official',
      confidence: 96,
      firstSeen: '2026-06-26',
      lastUpdate: '11 小时前',
      releaseWindow: '有限预览',
      title: 'GPT-5.6 Luna 随 GPT-5.6 系列发布',
      summary: 'Luna 与 Sol、Terra 同批进入有限范围发布，当前重点追踪 API 暴露、价格、评测和扩量窗口。',
      lane: 0,
      offset: 14,
      accent: '#8eb9ff',
      sources: [
        { name: 'OpenAI Help', type: 'docs', detail: '有限预览说明中包含 Luna', strength: 95, url: 'https://help.openai.com/' },
        { name: 'OpenAI API', type: 'platform', detail: '后续以模型列表和计费页为准', strength: 86, url: 'https://platform.openai.com/docs/models' },
      ],
    },
    {
      id: 'codex',
      provider: 'OpenAI',
      name: 'Codex',
      category: 'AI 编程',
      level: 'platform',
      confidence: 94,
      firstSeen: '32 分钟前',
      lastUpdate: '2 分钟前',
      releaseWindow: '持续更新',
      title: 'Codex 编程代理生态需要独立追踪',
      summary: 'Codex 不只是模型入口，而是 AI 编程工作流本身；需要持续追踪 CLI、IDE、任务线程、工具调用和 Skill 能力变化。',
      lane: 1,
      offset: 20,
      accent: '#8eb9ff',
      sources: [
        { name: 'OpenAI 开发者文档', type: 'docs', detail: '追踪 Codex、工具调用和开发者工作流变化', strength: 86, url: 'https://developers.openai.com/' },
        { name: 'GitHub 热度', type: 'platform', detail: '通过相关仓库增长观察生态扩散', strength: 74, url: 'https://github.com/search?q=codex+agent&type=repositories' },
      ],
    },
    {
      id: 'claude-code',
      provider: 'Anthropic',
      name: 'Claude Code',
      category: 'AI 编程',
      level: 'docs',
      confidence: 92,
      firstSeen: '1 小时前',
      lastUpdate: '4 分钟前',
      releaseWindow: '持续更新',
      title: 'Claude Code 成为 Anthropic 工具线重点',
      summary: 'Claude Code 代表模型能力向真实开发环境迁移，版本、权限、上下文和终端集成都值得长期追踪。',
      lane: 2,
      offset: 34,
      accent: '#ffb86b',
      sources: [
        { name: 'Claude Code 文档', type: 'docs', detail: '命令行、权限和项目上下文说明持续变化', strength: 84, url: 'https://code.claude.com/docs/' },
        { name: 'SkillsBench', type: 'benchmark', detail: '评估带 Skill 工作流的真实开发能力', strength: 74, url: 'https://www.skillsbench.ai/leaderboard' },
      ],
    },
    {
      id: 'mcp-skills',
      provider: 'MCP Ecosystem',
      name: 'MCP / Skills',
      category: 'Skill / 插件',
      level: 'docs',
      confidence: 88,
      firstSeen: '3 小时前',
      lastUpdate: '12 分钟前',
      releaseWindow: '持续更新',
      title: 'Skill 与 MCP 生态正在成为关键层',
      summary: '未来不只是模型强弱，工具调用、连接器、Skill、MCP Server 会决定 AI 能否真正处理复杂任务。',
      lane: 4,
      offset: 25,
      accent: '#b79cff',
      sources: [
        { name: '协议文档', type: 'docs', detail: 'MCP、工具规范和权限模型需要跟踪', strength: 83, url: 'https://modelcontextprotocol.io/' },
        { name: 'GitHub 仓库', type: 'platform', detail: '社区 MCP Server 增长可作生态热度', strength: 74, url: 'https://github.com/search?q=mcp+server&type=repositories' },
      ],
    },
    {
      id: 'agent-runtime',
      provider: 'OpenAI / Anthropic / LangChain',
      name: 'Agent Runtime',
      category: 'Agent',
      level: 'docs',
      confidence: 84,
      firstSeen: '4 小时前',
      lastUpdate: '14 分钟前',
      releaseWindow: '持续更新',
      title: 'Agent 运行时与工具权限成为前沿层',
      summary: 'Agent 不只是聊天界面，需要持续追踪任务执行、浏览器/终端能力、工具权限、记忆、沙箱和可观测性。',
      lane: 4,
      offset: 62,
      accent: '#f7d774',
      sources: [
        { name: 'Agent SDK 文档', type: 'docs', detail: 'Agent SDK、工具调用、沙箱和权限模型的变更', strength: 82, url: 'https://platform.openai.com/docs/agents' },
        { name: 'Agent 榜单', type: 'benchmark', detail: 'Steel、Agent Arena、HAL 等榜单提供外部评估', strength: 78, url: 'https://leaderboard.steel.dev/' },
      ],
    },
    {
      id: 'openrouter-rankings',
      provider: 'OpenRouter / LMArena',
      name: 'Rankings Signal',
      category: '平台',
      level: 'platform',
      confidence: 86,
      firstSeen: '5 小时前',
      lastUpdate: '16 分钟前',
      releaseWindow: '每日更新',
      title: '榜单变化需要和发布信号分开看',
      summary: '模型排名可以接入 OpenRouter、LMArena、Artificial Analysis、SWE-bench 等平台，但不能替代官方发布和文档变更。',
      lane: 5,
      offset: 12,
      accent: '#ff6fd8',
      sources: [
        { name: 'OpenRouter Models', type: 'platform', detail: '模型可用性、价格、上下文和模态', strength: 83, url: 'https://openrouter.ai/api/v1/models' },
        { name: 'LMArena', type: 'benchmark', detail: '社区偏好榜可作能力趋势参考', strength: 76, url: 'https://arena.ai/leaderboard' },
      ],
    },
    {
      id: 'gemini-31-pro',
      provider: 'Google',
      name: 'Gemini 3.1 Pro',
      category: '模型',
      level: 'platform',
      confidence: 91,
      firstSeen: '46 分钟前',
      lastUpdate: '6 分钟前',
      releaseWindow: '约 2-5 周',
      title: 'Gemini Pro 系列需要持续追踪产品接入信号',
      summary: 'Gemini 相关信号需要同时关注 Google 官方发布、AI Studio / Vertex AI 接入、第三方模型网关和开发者社区反馈。',
      lane: 2,
      offset: 41,
      accent: '#4b8cff',
      sources: [
        { name: 'Gemini API Changelog', type: 'docs', detail: '官方变更日志是最高权重来源', strength: 88, url: 'https://ai.google.dev/gemini-api/docs/changelog' },
        { name: 'AI Studio / Vertex AI', type: 'platform', detail: '产品接入和 API 可用性需要持续监测', strength: 86, url: 'https://ai.google.dev/' },
      ],
    },
    {
      id: 'deepseek-v4-pro',
      provider: 'DeepSeek',
      name: 'DeepSeek V4 Pro',
      category: '模型',
      level: 'rumor',
      confidence: 76,
      firstSeen: '7 小时前',
      lastUpdate: '18 分钟前',
      releaseWindow: '约 4-8 周',
      title: 'DeepSeek Pro 信号进入观察模式',
      summary: '需要把社区传闻、开源仓库、API 接入和官方公告拆开处理，避免把传闻当事实。',
      lane: 5,
      offset: 58,
      accent: '#58d68d',
      sources: [
        { name: 'DeepSeek API', type: 'docs', detail: '模型列表和价格页是确认信号', strength: 78, url: 'https://api-docs.deepseek.com/' },
        { name: '社区观察', type: 'social', detail: '讨论热度高，但需要证据链校准', strength: 52, url: 'https://x.com/search?q=DeepSeek%20model' },
      ],
    },
    {
      id: 'kimi-k26',
      provider: 'Moonshot',
      name: 'Kimi K2.6',
      category: '模型',
      level: 'platform',
      confidence: 80,
      firstSeen: '8 小时前',
      lastUpdate: '22 分钟前',
      releaseWindow: '约 3-6 周',
      title: 'Kimi 系列模型信号进入观察池',
      summary: 'Kimi 动态需要关注 Moonshot 官方渠道、产品侧模型选择器、API 文档和中文社区讨论。',
      lane: 5,
      offset: 72,
      accent: '#111827',
      sources: [
        { name: 'Kimi API 文档', type: 'docs', detail: '模型列表、价格和调用限制作为确认信号', strength: 75, url: 'https://platform.kimi.ai/docs/overview' },
        { name: '中文社区观察', type: 'social', detail: '讨论热度上升，但需要证据链校准', strength: 50, url: 'https://x.com/search?q=Kimi%20model' },
      ],
    },
  ],
  releaseFrames: [
    { name: 'GPT-5.6 Sol', provider: 'OpenAI', category: '模型', confidence: 99, window: '有限预览', accent: '#63f7d4' },
    { name: 'GPT-5.6 Terra', provider: 'OpenAI', category: '模型', confidence: 97, window: '有限预览', accent: '#ff8f5f' },
    { name: 'GPT-5.6 Luna', provider: 'OpenAI', category: '模型', confidence: 96, window: '有限预览', accent: '#8eb9ff' },
    { name: 'Codex', provider: 'OpenAI', category: 'AI 编程', confidence: 94, window: '持续更新', accent: '#8eb9ff' },
    { name: 'Claude Code', provider: 'Anthropic', category: 'AI 编程', confidence: 92, window: '持续更新', accent: '#ffb86b' },
    { name: 'Agent Runtime', provider: 'OpenAI / Anthropic / LangChain', category: 'Agent', confidence: 84, window: '持续更新', accent: '#f7d774' },
  ],
  rankingItems: [
    { rank: 1, name: 'GPT-5.6 Sol', provider: 'OpenAI', category: '模型', score: 99, change: 16, trend: [52, 58, 64, 70, 78, 91, 99], accent: '#63f7d4', kind: 'model' },
    { rank: 2, name: 'GPT-5.6 Terra', provider: 'OpenAI', category: '模型', score: 97, change: 14, trend: [48, 55, 61, 67, 75, 89, 97], accent: '#ff8f5f', kind: 'model' },
    { rank: 3, name: 'GPT-5.6 Luna', provider: 'OpenAI', category: '模型', score: 96, change: 13, trend: [46, 53, 58, 65, 73, 87, 96], accent: '#8eb9ff', kind: 'model' },
    { rank: 4, name: 'Codex', provider: 'OpenAI', category: 'AI 编程', score: 94, change: 8, trend: [32, 36, 40, 48, 55, 67, 75], accent: '#8eb9ff', kind: 'tool' },
    { rank: 5, name: 'Claude Code', provider: 'Anthropic', category: 'AI 编程', score: 92, change: 6, trend: [45, 49, 53, 52, 60, 63, 70], accent: '#ffb86b', kind: 'tool' },
    { rank: 6, name: 'Agent Runtime', provider: 'OpenAI / Anthropic', category: 'Agent', score: 84, change: 3, trend: [28, 34, 39, 48, 52, 58, 60], accent: '#f7d774', kind: 'agent' },
  ],
  sourceHealth: [
    { name: 'OpenAI 官方', detail: '官网、Help、API 模型列表', type: 'official', influence: 100, coverage: 99, accent: '#63f7d4', url: 'https://openai.com/news/', accessMethod: 'official-page', authRequired: false, freshnessSla: '30m-1h', weight: 1 },
    { name: 'OpenRouter Models', detail: '模型可用性、上下文、价格', type: 'platform', influence: 92, coverage: 91, accent: '#ff6fd8', url: 'https://openrouter.ai/api/v1/models', accessMethod: 'public-api', authRequired: false, freshnessSla: '1h', weight: 0.88 },
    { name: 'GitHub Search', detail: 'Agent / MCP / Coding 工具开源热度', type: 'platform', influence: 84, coverage: 88, accent: '#111827', url: 'https://docs.github.com/en/rest/search/search', accessMethod: 'public-api', authRequired: false, freshnessSla: '1h', weight: 0.62 },
    { name: 'Hacker News', detail: '社区讨论热度与评论密度', type: 'social', influence: 78, coverage: 82, accent: '#ff8f5f', url: 'https://hn.algolia.com/api', accessMethod: 'public-api', authRequired: false, freshnessSla: '30m', weight: 0.44 },
    { name: 'X / Twitter', detail: '官方账号与关键词传播，需要 API Key', type: 'social', influence: 76, coverage: 0, accent: '#111827', status: 'skipped', url: 'https://docs.x.com/x-api/posts/search-recent-posts', accessMethod: 'api-key', authRequired: true, freshnessSla: '15m', weight: 0.28 },
  ],
  sourceRuns: [],
  dataPanels: [
    {
      id: 'model-rankings',
      title: '模型排行榜',
      description: '官方确认 + OpenRouter + Artificial Analysis + LMArena + SWE-bench 的综合模型信号。',
      sources: ['OpenRouter', 'Artificial Analysis', 'LMArena', 'SWE-bench', '官方文档'],
      cadence: '6 小时',
      items: [
        { label: 'GPT-5.6 Sol', value: '99', note: '官方确认 + 有限预览', score: 99 },
        { label: 'GPT-5.6 Terra', value: '97', note: '官方确认 + 有限预览', score: 97 },
        { label: 'GPT-5.6 Luna', value: '96', note: '官方确认 + 有限预览', score: 96 },
      ],
    },
    {
      id: 'agent-rankings',
      title: 'Agent 排行榜',
      description: '浏览器、桌面、代码和研究 Agent 的 benchmark 与产品热度。',
      sources: ['Steel.dev', 'Agent Arena', 'HAL Princeton', 'SkillsBench', 'OSWorld'],
      cadence: '每日',
      items: [
        { label: 'Agent Runtime', value: '84', note: '运行时、工具权限、沙箱能力', score: 84 },
        { label: 'Claude Code', value: '82', note: '代码 Agent 与 Skill 工作流', score: 82 },
        { label: 'OpenHands / Devin / Manus', value: '观察', note: '需要榜单与 GitHub 交叉确认' },
      ],
    },
    {
      id: 'tool-rankings',
      title: '工具 / 插件热度',
      description: 'Product Hunt、GitHub、OSSInsight、HN 与 X 共同计算的工具热度。',
      sources: ['GitHub', 'OSSInsight', 'Product Hunt', 'HN Algolia', 'X'],
      cadence: '1 小时',
      items: [
        { label: 'MCP / Skills', value: '88', note: '社区 MCP Server 增长明显', score: 88 },
        { label: 'Codex', value: '94', note: 'AI 编程工作流入口', score: 94 },
        { label: 'Hammers / Hammer / Hermes', value: '候选', note: '先进入候选池，需两类来源确认' },
      ],
    },
  ],
  roadmapItems: [
    { version: 'v1.2', title: '真实数据刷新与 JSON 快照', quarter: 'Q2 2026', status: 'active' },
    { version: 'v1.3', title: 'MySQL 持久化与抓取日志', quarter: 'Q3 2026', status: 'active' },
    { version: 'v1.4', title: 'Agent 市场和插件生态图', quarter: 'Q3 2026', status: 'planned' },
    { version: 'v1.5', title: '智能摘要与异常热度告警', quarter: 'Q4 2026', status: 'planned' },
  ],
  languageOptions: [
    { code: 'zh-CN', label: '简体中文', status: 'active' },
    { code: 'en', label: 'English', status: 'planned' },
    { code: 'ja', label: '日本語', status: 'planned' },
  ],
}

export const fallbackRadarDataset = fallbackFrontierIntelDataset
export const workspaceNav = fallbackRadarDataset.workspaceNav
export const categories = fallbackRadarDataset.categories
export const categoryMeta = fallbackRadarDataset.categoryMeta
export const signals = fallbackRadarDataset.signals
export const releaseFrames = fallbackRadarDataset.releaseFrames
export const rankingItems = fallbackRadarDataset.rankingItems
export const sourceHealth = fallbackRadarDataset.sourceHealth
export const sourceRuns = fallbackRadarDataset.sourceRuns
export const dataPanels = fallbackRadarDataset.dataPanels
export const roadmapItems = fallbackRadarDataset.roadmapItems
export const languageOptions = fallbackRadarDataset.languageOptions
